name: Health Checker
on:
  schedule:
    - cron: '00 16 * * *'

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    name: Fill Out Health Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium --upgrade
          python -m pip install webdriver-manager --upgrade
      - name: Run HealthCheck
        run: |
          python3 HealthCheck.py
